 package com.nicadevelop.nicavpn.tools.sharedPreferences

 import io.michaelrocks.paranoid.Obfuscate

 @Obfuscate
 object DmPrefsKeys {
     //// BASURA
     const val SHARED_PREFERENCES_VPN_BY_IP = "SP_VPN_BY_IP"
     const val SHARED_PREFERENCES_VPN_BY_IP_DEFAULT = false
     const val SHARED_PREFERENCES_VPN_PASSWORD = "SP_VPN_PASSWORD"
     const val SHARED_PREFERENCES_VPN_PASSWORD_DEFAULT = "1270012323"
     ////
     const val SHARED_PREFERENCES_NAME = "ST_DIAM_PROXY"
     const val SHARED_PREFERENCES_SERVER = "SP_SERVER"
     const val SHARED_PREFERENCES_SERVER_DEFAULT = ""
     const val SHARED_PREFERENCES_SERVER_PORT = "SP_SERVER_PORT"
     const val SHARED_PREFERENCES_SERVER_PORT_DEFAULT: Long = 0
     const val SHARED_PREFERENCES_SNI = "SP_SNI"
     const val SHARED_PREFERENCES_SNI_DEFAULT = ""
     const val SHARED_PREFERENCES_DNS = "SP_DNS"
     const val SHARED_PREFERENCES_DNS_DEFAULT = ""
     const val SHARED_PREFERENCES_DNS_TT = "SP_DNS_TT"
     const val SHARED_PREFERENCES_DNS_TT_DEFAULT = "8.8.8.8:53"
     const val SHARED_PREFERENCES_DNS_TT_CONN = "SP_DNS_TT_CONN"
     const val SHARED_PREFERENCES_DNS_TT_CONN_DEFAULT = "UDP"
     const val SHARED_PREFERENCES_PING = "SP_PING"
     const val SHARED_PREFERENCES_PING_DEFAULT = 7000L
     const val SHARED_PREFERENCES_CUSTOM_PING = "SP_CUSTOM_PING"
     const val SHARED_PREFERENCES_CUSTOM_PING_DEFAULT = false
     const val SHARED_PREFERENCES_NEW_VERSION = "SP_NEW_APP_VERSION"
     const val SHARED_PREFERENCES_NEW_VERSION_DEFAULT = false

     const val SHARED_PREFERENCES_DNS_CONNECTION = "SP_DNS_CONNECTION"
     const val SHARED_PREFERENCES_DNS_CONNECTION_DEFAULT = false
     const val SHARED_PREFERENCES_TYPE_CONNECTION = "SP_TYPE_CONNECTION"
     const val SHARED_PREFERENCES_TYPE_CONNECTION_DEFAULT = "TLS Over HTTP"


     // Import file
     const val SHARED_PREFERENCES_IS_IMPORT_CF = "ST_DIAM_PROXY_IS_IMPORT_CF"
     const val SHARED_PREFERENCES_IS_IMPORT_CF_DEFAULT = false

     // http.request payload
     const val SHARED_PREFERENCES_PAYLOAD_CONFIG = "SP_PAYLOAD_CONFIG"
     const val SHARED_PREFERENCES_PAYLOAD_CONFIG_DEFAULT = ""

     // Payload generator
     const val SHARED_PREFERENCES_PG_XHOST = "xHost"
     const val SHARED_PREFERENCES_PG_XHOST_DEFAULT = ""
     const val SHARED_PREFERENCES_PG_REQUEST_METHOD = "RequestMethod"
     const val SHARED_PREFERENCES_PG_REQUEST_METHOD_DEFAULT = 0
     const val SHARED_PREFERENCES_PG_INJECT_METHOD = "InjectMethod"
     const val SHARED_PREFERENCES_PG_INJECT_METHOD_DEFAULT = 0
     const val SHARED_PREFERENCES_PG_XFRONT_QUERY = "xFrontQuery"
     const val SHARED_PREFERENCES_PG_XFRONT_QUERY_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XBACK_QUERY = "xBackQuery"
     const val SHARED_PREFERENCES_PG_XBACK_QUERY_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XONLINE_HOST = "xOnlineHost"
     const val SHARED_PREFERENCES_PG_XONLINE_HOST_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XFORWARDED_FOR = "xForwardedFor"
     const val SHARED_PREFERENCES_PG_XFORWARDED_FOR_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XFORWARD_HOST = "xForwardHost"
     const val SHARED_PREFERENCES_PG_XFORWARD_HOST_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XKEEP_ALIVE = "xKeepAlive"
     const val SHARED_PREFERENCES_PG_XKEEP_ALIVE_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XUSERAGENT = "xUserAgent"
     const val SHARED_PREFERENCES_PG_XUSERAGENT_DEFAULT = false
     const val SHARED_PREFERENCES_PG_USER_AGENT = "UserAgent"
     const val SHARED_PREFERENCES_PG_USER_AGENT_DEFAULT = 0
     const val SHARED_PREFERENCES_PG_XREAL_REQUEST = "xRealRequest"
     const val SHARED_PREFERENCES_PG_XREAL_REQUEST_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XDUAL_CONNECT = "xDualConnect"
     const val SHARED_PREFERENCES_PG_XDUAL_CONNECT_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XSPLIT_NO_DELAY = "xSplitNoDelay"
     const val SHARED_PREFERENCES_PG_XSPLIT_NO_DELAY_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XRADIO_GROUP = "xRadioGroup"
     const val SHARED_PREFERENCES_PG_XROTATION = "xRotation"
     const val SHARED_PREFERENCES_PG_XROTATION_DEFAULT = false
     const val SHARED_PREFERENCES_PG_XREFERER = "xReferer"
     const val SHARED_PREFERENCES_PG_XREFERER_DEFAULT = false

     // Custom File Export Message
     const val SHARED_PREFERENCES_FE_CUSTOM_MSG = "SP_PAYLOAD_FE_CUSTOM_MSG"
     const val SHARED_PREFERENCES_FE_CUSTOM_MSG_DEFAULT = ""

     const val SHARED_PREFERENCES_STARTED_PAYLOAD = "SP_STARTED_PAYLOAD_SERVICE"
     const val SHARED_PREFERENCES_STARTED_PAYLOAD_DEFAULT = false

     const val SHARED_PREFERENCES_STARTED_FAST_DNS = "SP_STARTED_FAST_DNS_SERVICE"
     const val SHARED_PREFERENCES_STARTED_FAST_DNS_DEFAULT = false

     const val SHARED_PREFERENCES_STARTED_UDP_MODE = "SP_STARTED_UDP_MODE_SERVICE"
     const val SHARED_PREFERENCES_STARTED_UDP_MODE_DEFAULT = false

     const val SHARED_PREFERENCES_STARTED_OPEN_VPN = "SP_STARTED_OPEN_VPN_SERVICE"
     const val SHARED_PREFERENCES_STARTED_OPEN_VPN_DEFAULT = false

     const val SHARED_PREFERENCES_STARTED_DNS_TT = "SP_STARTED_DNS_TT_SERVICE"
     const val SHARED_PREFERENCES_STARTED_DNS_TT_DEFAULT = false

     const val SHARED_PREFERENCES_FIRST_INSTALLATION = "SP_FIRST_INSTALATION"
     const val SHARED_PREFERENCES_FIRST_INSTALLATION_DEFAULT = true

     const val SHARED_PREFERENCES_FILE_NAME = "SP_PREFERENCES_FILE_NAME"
     const val SHARED_PREFERENCES_FILE_NAME_DEFAULT = ""

     const val SHARED_PREFERENCES_STARTED_VPN = "SP_STARTED_VPN"
     const val SHARED_PREFERENCES_STARTED_VPN_DEFAULT = false

     const val SHARED_PREFERENCES_BLOCK_CONF_SERVER = "SP_BLOCK_CONF_SERVER"

     const val SHARED_PREFERENCES_AUTOMATIC_CONNECTION = "SP_AUTOMATIC_CONNECTION"
     const val SHARED_PREFERENCES_AUTOMATIC_CONNECTION_DEFAULT = false

     const val SHARED_PREFERENCES_STARTED_V2RAY = "SP_STARTED_OPEN_VPN_SERVICE"
     const val SHARED_PREFERENCES_STARTED_V2RAY_DEFAULT = false
 }